#!/usr/bin/env python3
"""
Icon Base64 Converter

Scans the sibling icons/ directory for supported image files and generates
icons_byte64.py containing a dictionary mapping {name: base64_str}.

Usage:
    python3 icons.py

Supported extensions: .png, .jpg, .jpeg, .gif, .bmp
Note: Qt can directly display PNG/JPG/GIF/BMP.
    Vector/design sources (e.g., .svg, .ezdraw) are excluded so UI icons load reliably.
"""
import base64
import pathlib
import sys
from typing import Dict, Optional, Tuple

# Optional Qt imports for get_qicon helper
try:
    from PySide6 import QtGui, QtCore
except Exception:
    QtGui = None
    QtCore = None

ROOT = pathlib.Path(__file__).resolve().parent
SRC_DIR = ROOT  # scan current icons/ folder
OUT_FILE = ROOT / 'icons_byte64.py'
SUPPORTED = {'.png', '.jpg', '.jpeg', '.gif', '.bmp'}

HEADER = """# Auto-generated by icons/icons.py; do not edit.
ICONS = {
"""
FOOTER = """}

# Helper: decode base64 to bytes

def get_bytes(name: str):
    import base64
    s = ICONS.get(name)
    return base64.b64decode(s) if s else None
"""


def collect_icons() -> Dict[str, str]:
    icons: Dict[str, str] = {}
    for p in SRC_DIR.iterdir():
        if p.is_dir():
            # Skip __pycache__ and nested dirs (like icondesign) unless user expects
            # For now, include nested dirs too.
            for q in p.rglob('*'):
                if q.is_file() and q.suffix.lower() in SUPPORTED:
                    name = q.stem
                    try:
                        b64 = base64.b64encode(q.read_bytes()).decode('ascii')
                        icons[name] = b64
                    except Exception as e:
                        print(f"[warn] failed to encode {q}: {e}")
            continue
        if p.is_file() and p.suffix.lower() in SUPPORTED:
            name = p.stem
            try:
                b64 = base64.b64encode(p.read_bytes()).decode('ascii')
                icons[name] = b64
            except Exception as e:
                print(f"[warn] failed to encode {p}: {e}")
    return icons


def write_output(icons: Dict[str, str]) -> None:
    with OUT_FILE.open('w', encoding='utf-8') as f:
        f.write(HEADER)
        for name, b64 in sorted(icons.items()):
            # Safe repr; avoid triple quotes inside
            f.write(f"    '{name}': '{b64}',\n")
        f.write(FOOTER)
    print(f"[ok] wrote {OUT_FILE} with {len(icons)} icons")


if __name__ == '__main__':
    icons = collect_icons()
    write_output(icons)
    sys.exit(0)


# Library API: return QIcon from generated base64 mapping
def get_qicon(name: str, size: Optional[Tuple[int, int]] = None, tint: str | None = None):
    """Return a Qt QIcon for the given icon `name`.

    - Loads from icons/icons_byte64.py (generated by this script).
    - If `size` is provided, scales the pixmap to that size.
    - ``tint`` replaces the source RGB values while retaining the icon alpha.
    - Returns a fallback empty QIcon if PySide6 is unavailable or icon missing.
    """
    mirror_x = False
    if isinstance(name, str) and name.startswith('mirror:'):
        mirror_x = True
        name = name.split(':', 1)[1]

    try:
        from .icons_byte64 import ICONS  # type: ignore
    except Exception:
        ICONS = {}

    if QtGui is None:
        return None
    b64 = ICONS.get(name)
    if not b64:
        return QtGui.QIcon()
    try:
        ba = QtCore.QByteArray.fromBase64(b64.encode('ascii')) if QtCore else bytes()
        img = QtGui.QImage.fromData(ba)
        if img.isNull():
            return QtGui.QIcon()
        # High-DPI handling: scale to physical pixels and set devicePixelRatio
        dpr = 1.0
        try:
            scr = QtGui.QGuiApplication.primaryScreen()
            if scr:
                dpr = float(scr.devicePixelRatio())
        except Exception:
            dpr = 1.0
        if size:
            w_css, h_css = size
            w_px = max(1, int(round(w_css * dpr)))
            h_px = max(1, int(round(h_css * dpr)))
            # Use FastTransformation to avoid blur in small UI icons
            img = img.scaled(w_px, h_px, QtCore.Qt.AspectRatioMode.KeepAspectRatio, QtCore.Qt.TransformationMode.FastTransformation)

        if mirror_x:
            try:
                img = img.mirrored(True, False)
            except Exception:
                pass

        if tint is not None:
            color = QtGui.QColor(tint)
            if color.isValid():
                tinted = QtGui.QImage(img.size(), QtGui.QImage.Format.Format_ARGB32_Premultiplied)
                tinted.fill(color)
                alpha = img.convertToFormat(QtGui.QImage.Format.Format_Alpha8)
                painter = QtGui.QPainter(tinted)
                painter.setCompositionMode(QtGui.QPainter.CompositionMode.CompositionMode_DestinationIn)
                painter.drawImage(0, 0, alpha)
                painter.end()
                img = tinted

        pm = QtGui.QPixmap.fromImage(img)
        # Inform Qt of the device pixel ratio so it renders sharply at CSS size
        pm.setDevicePixelRatio(dpr)
        icon = QtGui.QIcon()
        icon.addPixmap(pm, QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        return icon
    except Exception:
        return QtGui.QIcon()
